name: Build VoicePro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          pip install uv
          cd ../zonos && uv venv && uv pip install -e .[compile]
          
      - name: Build application
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SAMPLES_PATH: ${{ vars.SAMPLES_PATH }}
        run: |
          npm run build:win
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: voicepro-windows
          path: |
            release/*.exe
            release/*.zip
          
  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    environment: production
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: voicepro-windows
          path: release
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}